---
- hosts: homeserver
  roles:
    - role: nvidia/drivers
      tags: 
        - nvidia

    - role: docker
      tags: 
        - docker

    - role: nvidia/container_runtime
      tags: 
        - nvidia

    - role: containers
      tags: 
        - containers

    - role: cloudalchemy.node_exporter
      tags:
        - monitoring

    - role: filesystem
      tags:
        - filesystem

    - role: bertvv.samba
      tags:
        - filesystem
      become: true
...