---
- hosts: homeserver
  roles:
    - role: nvidia/drivers
      tags: 
        - nvidia

    - role: docker
      tags: 
        - docker

    - role: nvidia/container_runtime
      tags: 
        - nvidia

    - role: containers
      tags: 
        - containers
...