---
- hosts: homeserver
  roles:
    - role: nvidia/drivers
      tags: 
        - nvidia

    - role: docker
      tags: 
        - docker

    - role: nvidia/container_runtime
      tags: 
        - nvidia

    - role: containers
      tags: 
        - containers

    - role: cloudalchemy.node_exporter
      vars:
        node_exporter_version: 1.3.1
      tags:
        - monitoring
...