---
- hosts: homeserver
  roles:
    - role: nvidia/drivers
      tags: 
        - nvidia

    - role: docker
      tags: 
        - docker

    - role: nvidia/container_runtime
      tags: 
        - nvidia

    - role: containers
      tags: 
        - containers

    - role: cloudalchemy.node_exporter
      tags:
        - monitoring

    - role: filesystem
      tags:
        - base
        - filesystem

    - role: bertvv.samba
      tags:
        - base
        - filesystem
      become: true

    - role: geerlingguy.ntp
      tags:
        - ntp
      become: base

    - role: jnv.unattended-upgrades
      tags:
        - base
      become: true
...