---
- name: Ensure directory for Samba shares exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0600"
    owner: "{{ username }}"
    group: "{{ username }}"
  become: true
  loop:
    - "{{ data_root_folder }}"
    - "{{ time_machine_root_folder }}"

- name: Add a cron for ZFS scrub
  ansible.builtin.cron:
    name: "Scrub {{ item.pool }} pool"
    minute: "0"
    hour: "2"
    day: "{{ item.day }}"
    job: "/sbin/zpool scrub {{ item.pool }}"
  become: true
  loop:
    - { pool: "tank", day: "1" }
    - { pool: "minitank", day: "7" }
...