---
- name: Create .containers directory
  ansible.builtin.file:
    path: '{{ containers_folder }}'
    state: directory
    mode: '0755'

- name: Create a group for each service
  ansible.builtin.group:
    name: '{{ item }}'
  become: true
  loop: '{{ services.keys() }}'

- name: Create a user for each service
  ansible.builtin.user:
    name: '{{ item }}'
    group: '{{ item }}'
    system: true
  register: users
  become: true
  loop: '{{ services.keys() }}'

- name: Setting users fact
  set_fact: users='{{ users | parse_uid_and_gid }}'

- name: Create appdata directories
  ansible.builtin.file:
    path: '{{ docker_persistant_folder }}/{{ item }}'
    state: directory
    owner: '{{ item }}'
    group: '{{ item }}'
    recurse: yes
  become: true
  loop: '{{ services | services_with_persistent_data }}'

- name: Create Secrets
  community.docker.docker_secret:
    name: '{{ item }}'
    data: '{{ lookup("vars", "{{ item }}") }}'
    state: present
  loop: '{{ services | extract_secrets_from_services }}'

- name: Copy templated docker-compose file
  ansible.builtin.template:
    src: templates/docker-compose.yaml.j2
    dest: '{{ containers_folder }}/docker-compose.yaml'
    mode: '0644'
    lstrip_blocks: true

- name: Copy templated traefik config file
  ansible.builtin.template:
    src: templates/traefik.yaml.j2
    dest: /opt/appdata/traefik/traefik.yaml
    mode: '0644'
    lstrip_blocks: true
  become: true

- name: Start all services
  community.general.docker_stack:
    state: present
    name: home
    compose:
      - '{{ containers_folder }}/docker-compose.yaml'
...