---
- name: Create .containers directory
  ansible.builtin.file:
    path: '{{ containers_folder }}'
    state: directory
    mode: '0755'

- name: Create appdata directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  become: true
  loop:
    - /opt/appdata/traefik
    - /opt/appdata/unifi

- name: Install dependencies for docker-compose ansible plugin
  ansible.builtin.apt:
    name:
      - python3-dev
      - python3-pip
    state: present
    update_cache: yes
  become: true

- name: Install Python modules for docker-compose ansible plugin
  ansible.builtin.pip:
    name:
      - docker-compose

- name: Initiate Docker Swarm
  community.docker.docker_swarm:
    state: present

- name: Create Secrets
  community.docker.docker_secret:
    name: '{{ item }}'
    data: '{{ lookup("vars", "{{ item }}") }}'
    state: present
  loop: '{{ services | extract_secrets_from_services }}'

- name: Copy templated docker-compose file
  ansible.builtin.template:
    src: templates/docker-compose.yaml.j2
    dest: '{{ containers_folder }}/docker-compose.yaml'
    mode: '0644'
    lstrip_blocks: true

- name: Copy templated traefik config file
  ansible.builtin.template:
    src: templates/traefik.yaml.j2
    dest: /opt/appdata/traefik/traefik.yaml
    mode: '0644'
    lstrip_blocks: true
  become: true

- name: Start all services
  community.general.docker_stack:
    state: present
    name: home
    compose:
      - '{{ containers_folder }}/docker-compose.yaml'
...