containers_folder: ~/.containers

services:
  traefik:
    image: traefik
    container_persistent_directory: /etc/traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.api@internal.loadbalancer.server.port=8080
    secrets:
      - CF_DNS_API_TOKEN

  unifi:
    image: linuxserver/unifi-controller
    container_persistent_directory: /config
    load_balancer_port: 8443
    labels:
      - traefik.http.services.unifi.loadbalancer.server.scheme=https
    ports:
      - 8080:8080
      - 3478:3478/udp

  flame:
    image: pawelmalak/flame
    container_persistent_directory: /app/data
    load_balancer_port: 5005
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  shepherd:
    image: mazzolino/shepherd
    no_load_balancer: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock