- name: Install Unifi Controller
  hosts: all
  become: yes
  
  tasks:
  - name: Install dependencies
    apt:
      name:
        - apt-transport-https
        - openjdk-8-jre-headless
      state: latest

  - name: Add Unifi Key
    apt_key:
      url: https://dl.ui.com/unifi/unifi-repo.gpg
      state: present

  - name: Add Unifi Repo
    apt_repository:
      repo: deb https://www.ui.com/downloads/unifi/debian stable ubiquiti
      state: present
      filename: 100-ubnt-unifi

  - name: Install Unifi
    apt:
      name: 
        - unifi
      update_cache: yes
      state: latest
