---
- name: Ensure Nvidia Container Runtime GPG Key is present
  ansible.builtin.apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present
  become: true

- name: Ensure Nvidia Container Runtime Repositories is present
  ansible.builtin.get_url:
    url: https://nvidia.github.io/nvidia-docker/{{ ansible_distribution|lower }}{{ ansible_distribution_version }}/nvidia-docker.list
    dest: /etc/apt/sources.list.d/nvidia-docker.list
    mode: '0644'
  become: true

- name: Ensure Nvidia Containers Runtime is installed
  ansible.builtin.apt:
    name:
      - nvidia-docker2
    state: present
    update_cache: yes
  become: true
  notify: Restart Docker service
...