---
- name: Ensure Docker dependencies are installed
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: true

- name: Ensure Docker GPG Key is present
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Ensure Docker Repository is present
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  become: true

- name: Ensure Docker is installed
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  become: true

- name: Ensure the username is part of the docker group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: yes
  become: true

- name: Install docker-compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  become: true
...